# Generated by Django 3.1.6 on 2021-07-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(max_length=10)),
                ('Description', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'Datas',
            },
        ),
    ]
