# Generated by Django 3.1.6 on 2021-08-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Section',
        ),
        migrations.AddField(
            model_name='data',
            name='chapter',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='data',
            name='chapter_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='data',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='data',
            name='section',
            field=models.CharField(default='', max_length=10),
        ),
    ]
