# Generated by Django 3.1.6 on 2021-08-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210801_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='section_name',
            field=models.CharField(default='', max_length=350),
        ),
    ]
