# Generated by Django 3.1.6 on 2021-08-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_data_section_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'IPC Sections'},
        ),
        migrations.AlterField(
            model_name='data',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
